export type NameMeaning = {
  name: string
  gender: "male" | "female" | "unisex"
  origin: string
  meaning: string
  personality: string[]
  element: "Fire" | "Water" | "Earth" | "Air"
  color: string
  luckyNumbers: number[]
}

const nameMeanings: Record<string, NameMeaning> = {
  James: {
    name: "James",
    gender: "male",
    origin: "Hebrew",
    meaning: "Supplanter or one who follows",
    personality: ["Confident", "Analytical", "Determined", "Practical"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [1, 4, 8],
  },
  Mary: {
    name: "Mary",
    gender: "female",
    origin: "Hebrew",
    meaning: "Bitter or beloved",
    personality: ["Nurturing", "Reliable", "Compassionate", "Intuitive"],
    element: "Water",
    color: "#1E90FF",
    luckyNumbers: [2, 7, 9],
  },
  John: {
    name: "John",
    gender: "male",
    origin: "Hebrew",
    meaning: "God is gracious",
    personality: ["Loyal", "Steady", "Thoughtful", "Reliable"],
    element: "Earth",
    color: "#006400",
    luckyNumbers: [3, 6, 9],
  },
  Patricia: {
    name: "Patricia",
    gender: "female",
    origin: "Latin",
    meaning: "Noble or patrician",
    personality: ["Elegant", "Dignified", "Responsible", "Organized"],
    element: "Air",
    color: "#9370DB",
    luckyNumbers: [1, 5, 8],
  },
  Robert: {
    name: "Robert",
    gender: "male",
    origin: "Germanic",
    meaning: "Bright fame",
    personality: ["Ambitious", "Intelligent", "Resourceful", "Logical"],
    element: "Air",
    color: "#4682B4",
    luckyNumbers: [2, 5, 7],
  },
  Jennifer: {
    name: "Jennifer",
    gender: "female",
    origin: "Welsh",
    meaning: "White wave or fair one",
    personality: ["Creative", "Friendly", "Adaptable", "Communicative"],
    element: "Water",
    color: "#40E0D0",
    luckyNumbers: [3, 7, 9],
  },
  Michael: {
    name: "Michael",
    gender: "male",
    origin: "Hebrew",
    meaning: "Who is like God?",
    personality: ["Protective", "Strong", "Courageous", "Principled"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [1, 5, 9],
  },
  Elizabeth: {
    name: "Elizabeth",
    gender: "female",
    origin: "Hebrew",
    meaning: "God is my oath",
    personality: ["Dignified", "Loyal", "Intelligent", "Graceful"],
    element: "Earth",
    color: "#8FBC8F",
    luckyNumbers: [2, 6, 8],
  },
  William: {
    name: "William",
    gender: "male",
    origin: "Germanic",
    meaning: "Resolute protector",
    personality: ["Determined", "Protective", "Reliable", "Strong-willed"],
    element: "Earth",
    color: "#556B2F",
    luckyNumbers: [4, 6, 8],
  },
  Linda: {
    name: "Linda",
    gender: "female",
    origin: "Spanish",
    meaning: "Beautiful",
    personality: ["Gentle", "Harmonious", "Artistic", "Kind"],
    element: "Air",
    color: "#DDA0DD",
    luckyNumbers: [2, 5, 7],
  },
  David: {
    name: "David",
    gender: "male",
    origin: "Hebrew",
    meaning: "Beloved",
    personality: ["Creative", "Friendly", "Artistic", "Sensitive"],
    element: "Water",
    color: "#4169E1",
    luckyNumbers: [1, 4, 7],
  },
  Barbara: {
    name: "Barbara",
    gender: "female",
    origin: "Greek",
    meaning: "Foreign woman",
    personality: ["Independent", "Strong", "Resourceful", "Determined"],
    element: "Fire",
    color: "#B22222",
    luckyNumbers: [3, 6, 9],
  },
  Richard: {
    name: "Richard",
    gender: "male",
    origin: "Germanic",
    meaning: "Strong ruler",
    personality: ["Confident", "Leader", "Ambitious", "Decisive"],
    element: "Fire",
    color: "#CD5C5C",
    luckyNumbers: [1, 8, 9],
  },
  Susan: {
    name: "Susan",
    gender: "female",
    origin: "Hebrew",
    meaning: "Lily",
    personality: ["Practical", "Organized", "Reliable", "Nurturing"],
    element: "Earth",
    color: "#2E8B57",
    luckyNumbers: [2, 4, 8],
  },
  Joseph: {
    name: "Joseph",
    gender: "male",
    origin: "Hebrew",
    meaning: "God will add",
    personality: ["Dependable", "Wise", "Nurturing", "Patient"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [3, 6, 9],
  },
  Jessica: {
    name: "Jessica",
    gender: "female",
    origin: "Hebrew",
    meaning: "Wealthy",
    personality: ["Generous", "Vibrant", "Sociable", "Expressive"],
    element: "Fire",
    color: "#FF6347",
    luckyNumbers: [1, 5, 9],
  },
  Thomas: {
    name: "Thomas",
    gender: "male",
    origin: "Aramaic",
    meaning: "Twin",
    personality: ["Analytical", "Thoughtful", "Curious", "Balanced"],
    element: "Air",
    color: "#87CEEB",
    luckyNumbers: [2, 5, 7],
  },
  Sarah: {
    name: "Sarah",
    gender: "female",
    origin: "Hebrew",
    meaning: "Princess",
    personality: ["Dignified", "Nurturing", "Wise", "Graceful"],
    element: "Water",
    color: "#5F9EA0",
    luckyNumbers: [3, 6, 9],
  },
  Charles: {
    name: "Charles",
    gender: "male",
    origin: "Germanic",
    meaning: "Free man",
    personality: ["Independent", "Dignified", "Intelligent", "Reserved"],
    element: "Air",
    color: "#6495ED",
    luckyNumbers: [1, 4, 7],
  },
  Karen: {
    name: "Karen",
    gender: "female",
    origin: "Danish",
    meaning: "Pure",
    personality: ["Assertive", "Organized", "Direct", "Principled"],
    element: "Fire",
    color: "#DC143C",
    luckyNumbers: [2, 5, 8],
  },
  Christopher: {
    name: "Christopher",
    gender: "male",
    origin: "Greek",
    meaning: "Bearer of Christ",
    personality: ["Helpful", "Kind", "Supportive", "Reliable"],
    element: "Water",
    color: "#4682B4",
    luckyNumbers: [3, 7, 9],
  },
  Nancy: {
    name: "Nancy",
    gender: "female",
    origin: "Hebrew",
    meaning: "Grace",
    personality: ["Elegant", "Compassionate", "Intuitive", "Gentle"],
    element: "Water",
    color: "#B0E0E6",
    luckyNumbers: [2, 4, 6],
  },
  Daniel: {
    name: "Daniel",
    gender: "male",
    origin: "Hebrew",
    meaning: "God is my judge",
    personality: ["Wise", "Just", "Thoughtful", "Principled"],
    element: "Earth",
    color: "#DAA520",
    luckyNumbers: [1, 5, 9],
  },
  Lisa: {
    name: "Lisa",
    gender: "female",
    origin: "Hebrew",
    meaning: "God's promise",
    personality: ["Devoted", "Intelligent", "Creative", "Spiritual"],
    element: "Air",
    color: "#9370DB",
    luckyNumbers: [3, 7, 8],
  },
  Matthew: {
    name: "Matthew",
    gender: "male",
    origin: "Hebrew",
    meaning: "Gift of God",
    personality: ["Generous", "Thoughtful", "Responsible", "Intelligent"],
    element: "Earth",
    color: "#556B2F",
    luckyNumbers: [2, 4, 8],
  },
  Betty: {
    name: "Betty",
    gender: "female",
    origin: "Hebrew",
    meaning: "Oath of God",
    personality: ["Reliable", "Practical", "Warm", "Traditional"],
    element: "Earth",
    color: "#8FBC8F",
    luckyNumbers: [1, 6, 9],
  },
  Anthony: {
    name: "Anthony",
    gender: "male",
    origin: "Latin",
    meaning: "Priceless one",
    personality: ["Valuable", "Unique", "Charismatic", "Determined"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [3, 5, 9],
  },
  Margaret: {
    name: "Margaret",
    gender: "female",
    origin: "Greek",
    meaning: "Pearl",
    personality: ["Precious", "Refined", "Elegant", "Wise"],
    element: "Water",
    color: "#E0FFFF",
    luckyNumbers: [2, 7, 9],
  },
  Mark: {
    name: "Mark",
    gender: "male",
    origin: "Latin",
    meaning: "Warlike",
    personality: ["Strong", "Direct", "Focused", "Protective"],
    element: "Fire",
    color: "#B22222",
    luckyNumbers: [1, 5, 8],
  },
  Sandra: {
    name: "Sandra",
    gender: "female",
    origin: "Greek",
    meaning: "Defender of mankind",
    personality: ["Protective", "Strong", "Loyal", "Courageous"],
    element: "Fire",
    color: "#CD5C5C",
    luckyNumbers: [3, 6, 9],
  },
  Donald: {
    name: "Donald",
    gender: "male",
    origin: "Scottish",
    meaning: "World ruler",
    personality: ["Ambitious", "Confident", "Leader", "Determined"],
    element: "Fire",
    color: "#FF6347",
    luckyNumbers: [1, 4, 9],
  },
  Ashley: {
    name: "Ashley",
    gender: "female",
    origin: "English",
    meaning: "Ash tree meadow",
    personality: ["Grounded", "Natural", "Peaceful", "Harmonious"],
    element: "Earth",
    color: "#2E8B57",
    luckyNumbers: [2, 5, 8],
  },
  Steven: {
    name: "Steven",
    gender: "male",
    origin: "Greek",
    meaning: "Crown",
    personality: ["Dignified", "Accomplished", "Respected", "Leader"],
    element: "Air",
    color: "#4169E1",
    luckyNumbers: [3, 6, 7],
  },
  Kimberly: {
    name: "Kimberly",
    gender: "female",
    origin: "English",
    meaning: "From the royal fortress meadow",
    personality: ["Regal", "Strong", "Protected", "Noble"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [1, 4, 8],
  },
  Paul: {
    name: "Paul",
    gender: "male",
    origin: "Latin",
    meaning: "Small or humble",
    personality: ["Modest", "Thoughtful", "Intelligent", "Determined"],
    element: "Earth",
    color: "#556B2F",
    luckyNumbers: [2, 5, 9],
  },
  Emily: {
    name: "Emily",
    gender: "female",
    origin: "Latin",
    meaning: "Rival or emulating",
    personality: ["Ambitious", "Competitive", "Driven", "Passionate"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [1, 3, 9],
  },
  Andrew: {
    name: "Andrew",
    gender: "male",
    origin: "Greek",
    meaning: "Manly or brave",
    personality: ["Courageous", "Strong", "Independent", "Adventurous"],
    element: "Fire",
    color: "#CD5C5C",
    luckyNumbers: [1, 5, 8],
  },
  Donna: {
    name: "Donna",
    gender: "female",
    origin: "Italian",
    meaning: "Lady",
    personality: ["Elegant", "Dignified", "Graceful", "Refined"],
    element: "Air",
    color: "#DDA0DD",
    luckyNumbers: [2, 7, 9],
  },
  Joshua: {
    name: "Joshua",
    gender: "male",
    origin: "Hebrew",
    meaning: "God is salvation",
    personality: ["Spiritual", "Protective", "Faithful", "Reliable"],
    element: "Water",
    color: "#4682B4",
    luckyNumbers: [3, 6, 9],
  },
  Michelle: {
    name: "Michelle",
    gender: "female",
    origin: "Hebrew",
    meaning: "Who is like God",
    personality: ["Unique", "Spiritual", "Strong", "Compassionate"],
    element: "Water",
    color: "#5F9EA0",
    luckyNumbers: [1, 5, 7],
  },
  Kenneth: {
    name: "Kenneth",
    gender: "male",
    origin: "Scottish",
    meaning: "Handsome",
    personality: ["Attractive", "Charming", "Confident", "Sociable"],
    element: "Air",
    color: "#6495ED",
    luckyNumbers: [2, 4, 8],
  },
  Carol: {
    name: "Carol",
    gender: "female",
    origin: "Germanic",
    meaning: "Free person",
    personality: ["Independent", "Spirited", "Joyful", "Expressive"],
    element: "Air",
    color: "#9370DB",
    luckyNumbers: [3, 6, 9],
  },
  Kevin: {
    name: "Kevin",
    gender: "male",
    origin: "Irish",
    meaning: "Handsome birth",
    personality: ["Attractive", "Charming", "Creative", "Intelligent"],
    element: "Water",
    color: "#4169E1",
    luckyNumbers: [1, 7, 8],
  },
  Amanda: {
    name: "Amanda",
    gender: "female",
    origin: "Latin",
    meaning: "Worthy of love",
    personality: ["Lovable", "Kind", "Deserving", "Compassionate"],
    element: "Water",
    color: "#B0E0E6",
    luckyNumbers: [2, 5, 9],
  },
  Brian: {
    name: "Brian",
    gender: "male",
    origin: "Irish",
    meaning: "High or noble",
    personality: ["Dignified", "Respected", "Principled", "Intelligent"],
    element: "Air",
    color: "#87CEEB",
    luckyNumbers: [1, 4, 7],
  },
  Dorothy: {
    name: "Dorothy",
    gender: "female",
    origin: "Greek",
    meaning: "Gift of God",
    personality: ["Blessed", "Generous", "Spiritual", "Kind"],
    element: "Earth",
    color: "#8FBC8F",
    luckyNumbers: [3, 6, 9],
  },
  George: {
    name: "George",
    gender: "male",
    origin: "Greek",
    meaning: "Farmer",
    personality: ["Grounded", "Practical", "Hardworking", "Reliable"],
    element: "Earth",
    color: "#DAA520",
    luckyNumbers: [2, 4, 8],
  },
  Melissa: {
    name: "Melissa",
    gender: "female",
    origin: "Greek",
    meaning: "Honey bee",
    personality: ["Industrious", "Sweet", "Busy", "Productive"],
    element: "Air",
    color: "#FFD700",
    luckyNumbers: [1, 5, 9],
  },
  Edward: {
    name: "Edward",
    gender: "male",
    origin: "English",
    meaning: "Wealthy guardian",
    personality: ["Protective", "Prosperous", "Responsible", "Reliable"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [2, 6, 8],
  },
  Deborah: {
    name: "Deborah",
    gender: "female",
    origin: "Hebrew",
    meaning: "Bee",
    personality: ["Industrious", "Organized", "Productive", "Leader"],
    element: "Air",
    color: "#FFD700",
    luckyNumbers: [3, 7, 9],
  },
  Ronald: {
    name: "Ronald",
    gender: "male",
    origin: "Norse",
    meaning: "Ruler's counselor",
    personality: ["Wise", "Advisor", "Thoughtful", "Intelligent"],
    element: "Air",
    color: "#4682B4",
    luckyNumbers: [1, 4, 7],
  },
  Stephanie: {
    name: "Stephanie",
    gender: "female",
    origin: "Greek",
    meaning: "Crown",
    personality: ["Regal", "Accomplished", "Leader", "Dignified"],
    element: "Fire",
    color: "#FF6347",
    luckyNumbers: [2, 5, 8],
  },
  Timothy: {
    name: "Timothy",
    gender: "male",
    origin: "Greek",
    meaning: "Honoring God",
    personality: ["Respectful", "Spiritual", "Honorable", "Principled"],
    element: "Water",
    color: "#5F9EA0",
    luckyNumbers: [3, 6, 9],
  },
  Rebecca: {
    name: "Rebecca",
    gender: "female",
    origin: "Hebrew",
    meaning: "To bind",
    personality: ["Connecting", "Loyal", "Committed", "Faithful"],
    element: "Earth",
    color: "#2E8B57",
    luckyNumbers: [1, 4, 8],
  },
  Jason: {
    name: "Jason",
    gender: "male",
    origin: "Greek",
    meaning: "Healer",
    personality: ["Compassionate", "Helpful", "Nurturing", "Wise"],
    element: "Water",
    color: "#4169E1",
    luckyNumbers: [2, 7, 9],
  },
  Laura: {
    name: "Laura",
    gender: "female",
    origin: "Latin",
    meaning: "Laurel tree",
    personality: ["Victorious", "Strong", "Accomplished", "Natural"],
    element: "Earth",
    color: "#8FBC8F",
    luckyNumbers: [1, 3, 9],
  },
  Jeffrey: {
    name: "Jeffrey",
    gender: "male",
    origin: "Germanic",
    meaning: "Divine peace",
    personality: ["Peaceful", "Spiritual", "Calm", "Harmonious"],
    element: "Water",
    color: "#B0E0E6",
    luckyNumbers: [2, 5, 8],
  },
  Helen: {
    name: "Helen",
    gender: "female",
    origin: "Greek",
    meaning: "Bright, shining one",
    personality: ["Radiant", "Intelligent", "Beautiful", "Illuminating"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [3, 6, 9],
  },
  Ryan: {
    name: "Ryan",
    gender: "male",
    origin: "Irish",
    meaning: "Little king",
    personality: ["Leader", "Confident", "Charismatic", "Ambitious"],
    element: "Fire",
    color: "#CD5C5C",
    luckyNumbers: [1, 5, 7],
  },
  Sharon: {
    name: "Sharon",
    gender: "female",
    origin: "Hebrew",
    meaning: "Plain",
    personality: ["Straightforward", "Honest", "Practical", "Reliable"],
    element: "Earth",
    color: "#DAA520",
    luckyNumbers: [2, 4, 8],
  },
  Jacob: {
    name: "Jacob",
    gender: "male",
    origin: "Hebrew",
    meaning: "Supplanter",
    personality: ["Strategic", "Determined", "Clever", "Persistent"],
    element: "Air",
    color: "#6495ED",
    luckyNumbers: [3, 6, 9],
  },
  Cynthia: {
    name: "Cynthia",
    gender: "female",
    origin: "Greek",
    meaning: "Moon goddess",
    personality: ["Mystical", "Intuitive", "Cyclical", "Illuminating"],
    element: "Water",
    color: "#E0FFFF",
    luckyNumbers: [1, 7, 9],
  },
  Gary: {
    name: "Gary",
    gender: "male",
    origin: "Germanic",
    meaning: "Spear",
    personality: ["Direct", "Focused", "Protective", "Strong"],
    element: "Fire",
    color: "#B22222",
    luckyNumbers: [2, 5, 8],
  },
  Kathleen: {
    name: "Kathleen",
    gender: "female",
    origin: "Greek",
    meaning: "Pure",
    personality: ["Clean", "Honest", "Virtuous", "Principled"],
    element: "Water",
    color: "#5F9EA0",
    luckyNumbers: [3, 6, 9],
  },
  Nicholas: {
    name: "Nicholas",
    gender: "male",
    origin: "Greek",
    meaning: "Victory of the people",
    personality: ["Triumphant", "Supportive", "Community-minded", "Successful"],
    element: "Air",
    color: "#87CEEB",
    luckyNumbers: [1, 4, 7],
  },
  Amy: {
    name: "Amy",
    gender: "female",
    origin: "Latin",
    meaning: "Beloved",
    personality: ["Lovable", "Friendly", "Warm", "Cherished"],
    element: "Water",
    color: "#B0E0E6",
    luckyNumbers: [2, 5, 8],
  },
  Eric: {
    name: "Eric",
    gender: "male",
    origin: "Norse",
    meaning: "Eternal ruler",
    personality: ["Enduring", "Leader", "Powerful", "Commanding"],
    element: "Fire",
    color: "#FF6347",
    luckyNumbers: [1, 3, 9],
  },
  Shirley: {
    name: "Shirley",
    gender: "female",
    origin: "English",
    meaning: "Bright meadow",
    personality: ["Bright", "Cheerful", "Open", "Natural"],
    element: "Earth",
    color: "#8FBC8F",
    luckyNumbers: [2, 6, 8],
  },
  Stephen: {
    name: "Stephen",
    gender: "male",
    origin: "Greek",
    meaning: "Crown",
    personality: ["Accomplished", "Dignified", "Respected", "Leader"],
    element: "Air",
    color: "#4682B4",
    luckyNumbers: [3, 5, 9],
  },
  Angela: {
    name: "Angela",
    gender: "female",
    origin: "Greek",
    meaning: "Messenger of God",
    personality: ["Communicative", "Spiritual", "Helpful", "Insightful"],
    element: "Air",
    color: "#9370DB",
    luckyNumbers: [1, 4, 7],
  },
  Jonathan: {
    name: "Jonathan",
    gender: "male",
    origin: "Hebrew",
    meaning: "Gift of God",
    personality: ["Generous", "Blessed", "Valuable", "Spiritual"],
    element: "Water",
    color: "#4169E1",
    luckyNumbers: [2, 5, 8],
  },
  Brenda: {
    name: "Brenda",
    gender: "female",
    origin: "Norse",
    meaning: "Sword",
    personality: ["Strong", "Direct", "Protective", "Decisive"],
    element: "Fire",
    color: "#CD5C5C",
    luckyNumbers: [3, 6, 9],
  },
  Justin: {
    name: "Justin",
    gender: "male",
    origin: "Latin",
    meaning: "Just or fair",
    personality: ["Fair", "Balanced", "Ethical", "Principled"],
    element: "Air",
    color: "#87CEEB",
    luckyNumbers: [1, 5, 7],
  },
  Catherine: {
    name: "Catherine",
    gender: "female",
    origin: "Greek",
    meaning: "Pure",
    personality: ["Virtuous", "Clear", "Honest", "Principled"],
    element: "Water",
    color: "#E0FFFF",
    luckyNumbers: [2, 4, 8],
  },
  Scott: {
    name: "Scott",
    gender: "male",
    origin: "Scottish",
    meaning: "From Scotland",
    personality: ["Proud", "Strong", "Traditional", "Independent"],
    element: "Earth",
    color: "#556B2F",
    luckyNumbers: [3, 6, 9],
  },
  Rachel: {
    name: "Rachel",
    gender: "female",
    origin: "Hebrew",
    meaning: "Ewe",
    personality: ["Gentle", "Nurturing", "Peaceful", "Kind"],
    element: "Earth",
    color: "#2E8B57",
    luckyNumbers: [1, 7, 9],
  },
  Brandon: {
    name: "Brandon",
    gender: "male",
    origin: "English",
    meaning: "Beacon hill",
    personality: ["Guiding", "Illuminating", "Prominent", "Visible"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [2, 5, 8],
  },
  Christine: {
    name: "Christine",
    gender: "female",
    origin: "Greek",
    meaning: "Follower of Christ",
    personality: ["Faithful", "Devoted", "Spiritual", "Principled"],
    element: "Water",
    color: "#5F9EA0",
    luckyNumbers: [3, 6, 9],
  },
  Benjamin: {
    name: "Benjamin",
    gender: "male",
    origin: "Hebrew",
    meaning: "Son of the right hand",
    personality: ["Favored", "Supportive", "Reliable", "Trustworthy"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [1, 4, 7],
  },
  Janet: {
    name: "Janet",
    gender: "female",
    origin: "Hebrew",
    meaning: "God's gracious gift",
    personality: ["Blessed", "Gracious", "Generous", "Kind"],
    element: "Water",
    color: "#B0E0E6",
    luckyNumbers: [2, 5, 8],
  },
  Samuel: {
    name: "Samuel",
    gender: "male",
    origin: "Hebrew",
    meaning: "Heard by God",
    personality: ["Spiritual", "Attentive", "Receptive", "Thoughtful"],
    element: "Air",
    color: "#6495ED",
    luckyNumbers: [3, 6, 9],
  },
  Emma: {
    name: "Emma",
    gender: "female",
    origin: "Germanic",
    meaning: "Universal",
    personality: ["Adaptable", "Inclusive", "Comprehensive", "Whole"],
    element: "Air",
    color: "#9370DB",
    luckyNumbers: [1, 5, 8],
  },
  Gregory: {
    name: "Gregory",
    gender: "male",
    origin: "Greek",
    meaning: "Watchful or alert",
    personality: ["Observant", "Protective", "Vigilant", "Aware"],
    element: "Fire",
    color: "#B22222",
    luckyNumbers: [2, 4, 9],
  },
  Nicole: {
    name: "Nicole",
    gender: "female",
    origin: "Greek",
    meaning: "Victory of the people",
    personality: ["Triumphant", "Supportive", "Community-minded", "Successful"],
    element: "Air",
    color: "#DDA0DD",
    luckyNumbers: [3, 7, 9],
  },
  Patrick: {
    name: "Patrick",
    gender: "male",
    origin: "Latin",
    meaning: "Nobleman",
    personality: ["Dignified", "Honorable", "Respected", "Principled"],
    element: "Earth",
    color: "#DAA520",
    luckyNumbers: [1, 5, 9],
  },
  Samantha: {
    name: "Samantha",
    gender: "female",
    origin: "Aramaic",
    meaning: "Listener",
    personality: ["Attentive", "Empathetic", "Understanding", "Receptive"],
    element: "Water",
    color: "#5F9EA0",
    luckyNumbers: [2, 6, 8],
  },
  Jack: {
    name: "Jack",
    gender: "male",
    origin: "Hebrew",
    meaning: "God is gracious",
    personality: ["Charming", "Energetic", "Adventurous", "Quick-witted"],
    element: "Fire",
    color: "#FF6347",
    luckyNumbers: [1, 3, 7],
  },
  Olivia: {
    name: "Olivia",
    gender: "female",
    origin: "Latin",
    meaning: "Olive tree",
    personality: ["Peaceful", "Fruitful", "Enduring", "Harmonious"],
    element: "Earth",
    color: "#8FBC8F",
    luckyNumbers: [2, 4, 8],
  },
  Henry: {
    name: "Henry",
    gender: "male",
    origin: "Germanic",
    meaning: "Ruler of the home",
    personality: ["Leader", "Protective", "Responsible", "Authoritative"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [3, 6, 9],
  },
  Sophia: {
    name: "Sophia",
    gender: "female",
    origin: "Greek",
    meaning: "Wisdom",
    personality: ["Intelligent", "Thoughtful", "Insightful", "Wise"],
    element: "Air",
    color: "#9370DB",
    luckyNumbers: [1, 7, 9],
  },
  Alexander: {
    name: "Alexander",
    gender: "male",
    origin: "Greek",
    meaning: "Defender of the people",
    personality: ["Protective", "Strong", "Courageous", "Loyal"],
    element: "Fire",
    color: "#CD5C5C",
    luckyNumbers: [1, 5, 8],
  },
  Isabella: {
    name: "Isabella",
    gender: "female",
    origin: "Hebrew",
    meaning: "Devoted to God",
    personality: ["Faithful", "Devoted", "Spiritual", "Committed"],
    element: "Water",
    color: "#E0FFFF",
    luckyNumbers: [2, 4, 7],
  },
  Noah: {
    name: "Noah",
    gender: "male",
    origin: "Hebrew",
    meaning: "Rest or comfort",
    personality: ["Peaceful", "Calming", "Reliable", "Nurturing"],
    element: "Water",
    color: "#4682B4",
    luckyNumbers: [3, 6, 9],
  },
  Charlotte: {
    name: "Charlotte",
    gender: "female",
    origin: "French",
    meaning: "Free",
    personality: ["Independent", "Strong-willed", "Liberated", "Expressive"],
    element: "Air",
    color: "#DDA0DD",
    luckyNumbers: [1, 5, 8],
  },
  Liam: {
    name: "Liam",
    gender: "male",
    origin: "Irish",
    meaning: "Strong-willed warrior",
    personality: ["Determined", "Brave", "Resolute", "Protective"],
    element: "Fire",
    color: "#B22222",
    luckyNumbers: [2, 7, 9],
  },
  Ava: {
    name: "Ava",
    gender: "female",
    origin: "Latin",
    meaning: "Life",
    personality: ["Vibrant", "Energetic", "Lively", "Spirited"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [1, 3, 9],
  },
  Ethan: {
    name: "Ethan",
    gender: "male",
    origin: "Hebrew",
    meaning: "Strong, firm",
    personality: ["Reliable", "Steadfast", "Enduring", "Solid"],
    element: "Earth",
    color: "#556B2F",
    luckyNumbers: [2, 4, 8],
  },
  Mia: {
    name: "Mia",
    gender: "female",
    origin: "Italian",
    meaning: "Mine",
    personality: ["Possessive", "Passionate", "Devoted", "Intense"],
    element: "Fire",
    color: "#FF6347",
    luckyNumbers: [3, 6, 9],
  },
  Mason: {
    name: "Mason",
    gender: "male",
    origin: "English",
    meaning: "Stone worker",
    personality: ["Skilled", "Crafty", "Hardworking", "Precise"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [1, 5, 7],
  },
  Amelia: {
    name: "Amelia",
    gender: "female",
    origin: "Germanic",
    meaning: "Work",
    personality: ["Industrious", "Diligent", "Productive", "Focused"],
    element: "Earth",
    color: "#2E8B57",
    luckyNumbers: [2, 4, 8],
  },
  Logan: {
    name: "Logan",
    gender: "male",
    origin: "Scottish",
    meaning: "Small hollow",
    personality: ["Thoughtful", "Deep", "Introspective", "Quiet"],
    element: "Water",
    color: "#4169E1",
    luckyNumbers: [3, 6, 9],
  },
  Harper: {
    name: "Harper",
    gender: "female",
    origin: "English",
    meaning: "Harp player",
    personality: ["Musical", "Artistic", "Creative", "Expressive"],
    element: "Air",
    color: "#9370DB",
    luckyNumbers: [1, 5, 8],
  },
  Lucas: {
    name: "Lucas",
    gender: "male",
    origin: "Greek",
    meaning: "Bringer of light",
    personality: ["Illuminating", "Bright", "Insightful", "Enlightening"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [2, 7, 9],
  },
  Evelyn: {
    name: "Evelyn",
    gender: "female",
    origin: "Hebrew",
    meaning: "Life",
    personality: ["Vibrant", "Energetic", "Lively", "Spirited"],
    element: "Fire",
    color: "#CD5C5C",
    luckyNumbers: [1, 3, 9],
  },
  Aiden: {
    name: "Aiden",
    gender: "male",
    origin: "Irish",
    meaning: "Little fire",
    personality: ["Passionate", "Energetic", "Warm", "Spirited"],
    element: "Fire",
    color: "#B22222",
    luckyNumbers: [2, 5, 8],
  },
  Abigail: {
    name: "Abigail",
    gender: "female",
    origin: "Hebrew",
    meaning: "Father's joy",
    personality: ["Joyful", "Delightful", "Pleasing", "Cheerful"],
    element: "Air",
    color: "#DDA0DD",
    luckyNumbers: [3, 6, 9],
  },
  Elijah: {
    name: "Elijah",
    gender: "male",
    origin: "Hebrew",
    meaning: "Yahweh is God",
    personality: ["Spiritual", "Faithful", "Principled", "Devoted"],
    element: "Air",
    color: "#6495ED",
    luckyNumbers: [1, 4, 7],
  },
  Elizabeth: {
    name: "Elizabeth",
    gender: "female",
    origin: "Hebrew",
    meaning: "God is my oath",
    personality: ["Faithful", "Committed", "Principled", "Loyal"],
    element: "Water",
    color: "#5F9EA0",
    luckyNumbers: [2, 5, 8],
  },
  Oliver: {
    name: "Oliver",
    gender: "male",
    origin: "Latin",
    meaning: "Olive tree",
    personality: ["Peaceful", "Fruitful", "Enduring", "Harmonious"],
    element: "Earth",
    color: "#8FBC8F",
    luckyNumbers: [3, 6, 9],
  },
  Sofia: {
    name: "Sofia",
    gender: "female",
    origin: "Greek",
    meaning: "Wisdom",
    personality: ["Intelligent", "Thoughtful", "Insightful", "Wise"],
    element: "Air",
    color: "#9370DB",
    luckyNumbers: [1, 7, 9],
  },
  Caleb: {
    name: "Caleb",
    gender: "male",
    origin: "Hebrew",
    meaning: "Faithful, devoted",
    personality: ["Loyal", "Committed", "Trustworthy", "Reliable"],
    element: "Earth",
    color: "#DAA520",
    luckyNumbers: [2, 4, 8],
  },
  Avery: {
    name: "Avery",
    gender: "unisex",
    origin: "English",
    meaning: "Ruler of the elves",
    personality: ["Magical", "Imaginative", "Leader", "Creative"],
    element: "Air",
    color: "#9370DB",
    luckyNumbers: [1, 5, 9],
  },
  Jackson: {
    name: "Jackson",
    gender: "male",
    origin: "English",
    meaning: "Son of Jack",
    personality: ["Energetic", "Adventurous", "Quick-witted", "Charming"],
    element: "Fire",
    color: "#FF6347",
    luckyNumbers: [2, 6, 8],
  },
  Scarlett: {
    name: "Scarlett",
    gender: "female",
    origin: "English",
    meaning: "Red",
    personality: ["Passionate", "Bold", "Vibrant", "Striking"],
    element: "Fire",
    color: "#DC143C",
    luckyNumbers: [3, 5, 9],
  },
  Gabriel: {
    name: "Gabriel",
    gender: "male",
    origin: "Hebrew",
    meaning: "God is my strength",
    personality: ["Strong", "Spiritual", "Messenger", "Communicative"],
    element: "Air",
    color: "#87CEEB",
    luckyNumbers: [1, 4, 7],
  },
  Victoria: {
    name: "Victoria",
    gender: "female",
    origin: "Latin",
    meaning: "Victory",
    personality: ["Triumphant", "Successful", "Accomplished", "Regal"],
    element: "Fire",
    color: "#CD5C5C",
    luckyNumbers: [2, 5, 8],
  },
  Owen: {
    name: "Owen",
    gender: "male",
    origin: "Welsh",
    meaning: "Young warrior",
    personality: ["Brave", "Youthful", "Energetic", "Courageous"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [3, 6, 9],
  },
  Madison: {
    name: "Madison",
    gender: "female",
    origin: "English",
    meaning: "Son of Matthew",
    personality: ["Strong", "Independent", "Adaptable", "Modern"],
    element: "Earth",
    color: "#2E8B57",
    luckyNumbers: [1, 4, 8],
  },
  Carter: {
    name: "Carter",
    gender: "male",
    origin: "English",
    meaning: "Transporter of goods",
    personality: ["Reliable", "Hardworking", "Practical", "Dependable"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [2, 5, 7],
  },
  Chloe: {
    name: "Chloe",
    gender: "female",
    origin: "Greek",
    meaning: "Blooming",
    personality: ["Flourishing", "Vibrant", "Growing", "Fresh"],
    element: "Earth",
    color: "#8FBC8F",
    luckyNumbers: [3, 6, 9],
  },
  Grayson: {
    name: "Grayson",
    gender: "male",
    origin: "English",
    meaning: "Son of the steward",
    personality: ["Responsible", "Trustworthy", "Reliable", "Dignified"],
    element: "Air",
    color: "#6495ED",
    luckyNumbers: [1, 5, 8],
  },
  Lily: {
    name: "Lily",
    gender: "female",
    origin: "English",
    meaning: "Pure",
    personality: ["Innocent", "Beautiful", "Delicate", "Graceful"],
    element: "Water",
    color: "#E0FFFF",
    luckyNumbers: [2, 4, 9],
  },
  Luke: {
    name: "Luke",
    gender: "male",
    origin: "Greek",
    meaning: "Light-giving",
    personality: ["Illuminating", "Bright", "Insightful", "Enlightening"],
    element: "Fire",
    color: "#FF6347",
    luckyNumbers: [3, 7, 9],
  },
  Eleanor: {
    name: "Eleanor",
    gender: "female",
    origin: "Greek",
    meaning: "Bright, shining one",
    personality: ["Radiant", "Intelligent", "Illuminating", "Bright"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [1, 6, 8],
  },
  Isaac: {
    name: "Isaac",
    gender: "male",
    origin: "Hebrew",
    meaning: "Laughter",
    personality: ["Joyful", "Humorous", "Cheerful", "Light-hearted"],
    element: "Air",
    color: "#87CEEB",
    luckyNumbers: [2, 5, 7],
  },
  Hannah: {
    name: "Hannah",
    gender: "female",
    origin: "Hebrew",
    meaning: "Grace",
    personality: ["Graceful", "Elegant", "Poised", "Dignified"],
    element: "Water",
    color: "#B0E0E6",
    luckyNumbers: [3, 6, 9],
  },
  Wyatt: {
    name: "Wyatt",
    gender: "male",
    origin: "English",
    meaning: "Brave in war",
    personality: ["Courageous", "Strong", "Fearless", "Bold"],
    element: "Fire",
    color: "#B22222",
    luckyNumbers: [1, 4, 7],
  },
  Addison: {
    name: "Addison",
    gender: "female",
    origin: "English",
    meaning: "Son of Adam",
    personality: ["Original", "First", "Pioneering", "Innovative"],
    element: "Earth",
    color: "#DAA520",
    luckyNumbers: [2, 5, 8],
  },
  Julian: {
    name: "Julian",
    gender: "male",
    origin: "Latin",
    meaning: "Youthful",
    personality: ["Young-spirited", "Vibrant", "Energetic", "Fresh"],
    element: "Air",
    color: "#6495ED",
    luckyNumbers: [3, 6, 9],
  },
  Aubrey: {
    name: "Aubrey",
    gender: "female",
    origin: "Germanic",
    meaning: "Elf ruler",
    personality: ["Magical", "Leader", "Imaginative", "Powerful"],
    element: "Air",
    color: "#9370DB",
    luckyNumbers: [1, 5, 8],
  },
  Jaxon: {
    name: "Jaxon",
    gender: "male",
    origin: "English",
    meaning: "Son of Jack",
    personality: ["Energetic", "Modern", "Bold", "Distinctive"],
    element: "Fire",
    color: "#FF6347",
    luckyNumbers: [2, 7, 9],
  },
  Leah: {
    name: "Leah",
    gender: "female",
    origin: "Hebrew",
    meaning: "Weary",
    personality: ["Enduring", "Patient", "Persistent", "Strong"],
    element: "Earth",
    color: "#8FBC8F",
    luckyNumbers: [1, 3, 9],
  },
  Christopher: {
    name: "Christopher",
    gender: "male",
    origin: "Greek",
    meaning: "Bearer of Christ",
    personality: ["Helpful", "Supportive", "Caring", "Strong"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [2, 4, 8],
  },
  Zoe: {
    name: "Zoe",
    gender: "female",
    origin: "Greek",
    meaning: "Life",
    personality: ["Vibrant", "Energetic", "Lively", "Spirited"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [3, 6, 9],
  },
  Josiah: {
    name: "Josiah",
    gender: "male",
    origin: "Hebrew",
    meaning: "God supports",
    personality: ["Supported", "Faithful", "Spiritual", "Grounded"],
    element: "Earth",
    color: "#DAA520",
    luckyNumbers: [1, 5, 7],
  },
  Nora: {
    name: "Nora",
    gender: "female",
    origin: "Latin",
    meaning: "Honor",
    personality: ["Honorable", "Dignified", "Respected", "Principled"],
    element: "Air",
    color: "#DDA0DD",
    luckyNumbers: [2, 4, 8],
  },
  Hudson: {
    name: "Hudson",
    gender: "male",
    origin: "English",
    meaning: "Son of Hugh",
    personality: ["Intelligent", "Thoughtful", "Bright", "Perceptive"],
    element: "Water",
    color: "#4682B4",
    luckyNumbers: [3, 6, 9],
  },
  Stella: {
    name: "Stella",
    gender: "female",
    origin: "Latin",
    meaning: "Star",
    personality: ["Bright", "Shining", "Prominent", "Guiding"],
    element: "Fire",
    color: "#FFD700",
    luckyNumbers: [1, 5, 8],
  },
  Eli: {
    name: "Eli",
    gender: "male",
    origin: "Hebrew",
    meaning: "Ascended, uplifted",
    personality: ["Spiritual", "Elevated", "Enlightened", "Wise"],
    element: "Air",
    color: "#87CEEB",
    luckyNumbers: [2, 7, 9],
  },
  Grace: {
    name: "Grace",
    gender: "female",
    origin: "Latin",
    meaning: "Charm, goodness",
    personality: ["Elegant", "Poised", "Kind", "Refined"],
    element: "Water",
    color: "#E0FFFF",
    luckyNumbers: [1, 3, 9],
  },
  Ezra: {
    name: "Ezra",
    gender: "male",
    origin: "Hebrew",
    meaning: "Helper",
    personality: ["Supportive", "Helpful", "Caring", "Reliable"],
    element: "Earth",
    color: "#556B2F",
    luckyNumbers: [2, 4, 8],
  },
  Zoey: {
    name: "Zoey",
    gender: "female",
    origin: "Greek",
    meaning: "Life",
    personality: ["Vibrant", "Energetic", "Lively", "Spirited"],
    element: "Fire",
    color: "#FF6347",
    luckyNumbers: [3, 6, 9],
  },
  Colton: {
    name: "Colton",
    gender: "male",
    origin: "English",
    meaning: "From the dark town",
    personality: ["Mysterious", "Deep", "Thoughtful", "Introspective"],
    element: "Water",
    color: "#4169E1",
    luckyNumbers: [1, 5, 7],
  },
  Penelope: {
    name: "Penelope",
    gender: "female",
    origin: "Greek",
    meaning: "Weaver",
    personality: ["Creative", "Patient", "Detailed", "Artistic"],
    element: "Earth",
    color: "#2E8B57",
    luckyNumbers: [2, 4, 8],
  },
  Aaron: {
    name: "Aaron",
    gender: "male",
    origin: "Hebrew",
    meaning: "Exalted, strong",
    personality: ["Powerful", "Respected", "Dignified", "Strong"],
    element: "Fire",
    color: "#CD5C5C",
    luckyNumbers: [3, 6, 9],
  },
  Layla: {
    name: "Layla",
    gender: "female",
    origin: "Arabic",
    meaning: "Night",
    personality: ["Mysterious", "Deep", "Dreamy", "Intuitive"],
    element: "Water",
    color: "#5F9EA0",
    luckyNumbers: [1, 7, 9],
  },
  Landon: {
    name: "Landon",
    gender: "male",
    origin: "English",
    meaning: "Long hill",
    personality: ["Enduring", "Steady", "Grounded", "Persistent"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [2, 5, 8],
  },
  Riley: {
    name: "Riley",
    gender: "unisex",
    origin: "Irish",
    meaning: "Valiant",
    personality: ["Brave", "Courageous", "Bold", "Spirited"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [3, 6, 9],
  },
  Cameron: {
    name: "Cameron",
    gender: "unisex",
    origin: "Scottish",
    meaning: "Crooked nose",
    personality: ["Distinctive", "Unique", "Memorable", "Characterful"],
    element: "Air",
    color: "#6495ED",
    luckyNumbers: [1, 4, 7],
  },
  Savannah: {
    name: "Savannah",
    gender: "female",
    origin: "Spanish",
    meaning: "Flat tropical grassland",
    personality: ["Open", "Free", "Natural", "Expansive"],
    element: "Earth",
    color: "#8FBC8F",
    luckyNumbers: [2, 5, 8],
  },
  Jeremiah: {
    name: "Jeremiah",
    gender: "male",
    origin: "Hebrew",
    meaning: "Appointed by God",
    personality: ["Chosen", "Special", "Spiritual", "Purposeful"],
    element: "Water",
    color: "#4682B4",
    luckyNumbers: [3, 6, 9],
  },
  Hailey: {
    name: "Hailey",
    gender: "female",
    origin: "English",
    meaning: "Hay meadow",
    personality: ["Natural", "Peaceful", "Serene", "Grounded"],
    element: "Earth",
    color: "#DAA520",
    luckyNumbers: [1, 5, 8],
  },
  Christian: {
    name: "Christian",
    gender: "male",
    origin: "Greek",
    meaning: "Follower of Christ",
    personality: ["Faithful", "Devoted", "Principled", "Spiritual"],
    element: "Water",
    color: "#5F9EA0",
    luckyNumbers: [2, 4, 7],
  },
  Autumn: {
    name: "Autumn",
    gender: "female",
    origin: "Latin",
    meaning: "Fall season",
    personality: ["Colorful", "Transitional", "Mature", "Reflective"],
    element: "Earth",
    color: "#CD853F",
    luckyNumbers: [3, 6, 9],
  },
  Hunter: {
    name: "Hunter",
    gender: "male",
    origin: "English",
    meaning: "One who hunts",
    personality: ["Focused", "Determined", "Patient", "Strategic"],
    element: "Earth",
    color: "#556B2F",
    luckyNumbers: [1, 5, 9],
  },
  Quinn: {
    name: "Quinn",
    gender: "unisex",
    origin: "Irish",
    meaning: "Counsel",
    personality: ["Wise", "Thoughtful", "Advisor", "Intelligent"],
    element: "Air",
    color: "#9370DB",
    luckyNumbers: [2, 7, 8],
  },
  Asher: {
    name: "Asher",
    gender: "male",
    origin: "Hebrew",
    meaning: "Fortunate, blessed",
    personality: ["Lucky", "Blessed", "Prosperous", "Fortunate"],
    element: "Fire",
    color: "#FF6347",
    luckyNumbers: [1, 3, 9],
  },
  Eva: {
    name: "Eva",
    gender: "female",
    origin: "Hebrew",
    meaning: "Life",
    personality: ["Vibrant", "Lively", "Energetic", "Spirited"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [2, 4, 8],
  },
  Dominic: {
    name: "Dominic",
    gender: "male",
    origin: "Latin",
    meaning: "Belonging to the Lord",
    personality: ["Devoted", "Spiritual", "Faithful", "Principled"],
    element: "Water",
    color: "#4169E1",
    luckyNumbers: [3, 6, 9],
  },
  Brooklyn: {
    name: "Brooklyn",
    gender: "female",
    origin: "English",
    meaning: "Broken land",
    personality: ["Urban", "Modern", "Diverse", "Resilient"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [1, 5, 7],
  },
  Austin: {
    name: "Austin",
    gender: "male",
    origin: "Latin",
    meaning: "Magnificent",
    personality: ["Impressive", "Grand", "Dignified", "Respected"],
    element: "Fire",
    color: "#CD5C5C",
    luckyNumbers: [2, 4, 8],
  },
  Bella: {
    name: "Bella",
    gender: "female",
    origin: "Italian",
    meaning: "Beautiful",
    personality: ["Attractive", "Charming", "Elegant", "Graceful"],
    element: "Water",
    color: "#E0FFFF",
    luckyNumbers: [3, 6, 9],
  },
  Jordan: {
    name: "Jordan",
    gender: "unisex",
    origin: "Hebrew",
    meaning: "To flow down",
    personality: ["Fluid", "Adaptable", "Flowing", "Flexible"],
    element: "Water",
    color: "#4682B4",
    luckyNumbers: [1, 5, 8],
  },
  Claire: {
    name: "Claire",
    gender: "female",
    origin: "Latin",
    meaning: "Clear, bright",
    personality: ["Transparent", "Honest", "Illuminating", "Intelligent"],
    element: "Air",
    color: "#87CEEB",
    luckyNumbers: [2, 7, 9],
  },
  Adam: {
    name: "Adam",
    gender: "male",
    origin: "Hebrew",
    meaning: "Man, earth",
    personality: ["Grounded", "Original", "Natural", "Fundamental"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [1, 4, 7],
  },
  Skylar: {
    name: "Skylar",
    gender: "unisex",
    origin: "Dutch",
    meaning: "Scholar",
    personality: ["Intelligent", "Learned", "Academic", "Thoughtful"],
    element: "Air",
    color: "#87CEEB",
    luckyNumbers: [2, 5, 8],
  },
  Nolan: {
    name: "Nolan",
    gender: "male",
    origin: "Irish",
    meaning: "Champion",
    personality: ["Victorious", "Successful", "Accomplished", "Triumphant"],
    element: "Fire",
    color: "#B22222",
    luckyNumbers: [3, 6, 9],
  },
  Lucy: {
    name: "Lucy",
    gender: "female",
    origin: "Latin",
    meaning: "Light",
    personality: ["Bright", "Illuminating", "Radiant", "Cheerful"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [1, 5, 8],
  },
  Evan: {
    name: "Evan",
    gender: "male",
    origin: "Welsh",
    meaning: "Young warrior",
    personality: ["Youthful", "Brave", "Energetic", "Courageous"],
    element: "Fire",
    color: "#FF6347",
    luckyNumbers: [2, 4, 9],
  },
  Audrey: {
    name: "Audrey",
    gender: "female",
    origin: "English",
    meaning: "Noble strength",
    personality: ["Strong", "Dignified", "Respected", "Powerful"],
    element: "Earth",
    color: "#2E8B57",
    luckyNumbers: [3, 6, 7],
  },
  Angel: {
    name: "Angel",
    gender: "unisex",
    origin: "Greek",
    meaning: "Messenger",
    personality: ["Communicative", "Spiritual", "Pure", "Helpful"],
    element: "Air",
    color: "#E0FFFF",
    luckyNumbers: [1, 7, 9],
  },
  Violet: {
    name: "Violet",
    gender: "female",
    origin: "Latin",
    meaning: "Purple flower",
    personality: ["Delicate", "Beautiful", "Colorful", "Graceful"],
    element: "Earth",
    color: "#9370DB",
    luckyNumbers: [2, 5, 8],
  },
  Jose: {
    name: "Jose",
    gender: "male",
    origin: "Hebrew",
    meaning: "God will add",
    personality: ["Blessed", "Growing", "Expanding", "Prosperous"],
    element: "Water",
    color: "#4169E1",
    luckyNumbers: [3, 6, 9],
  },
  Aria: {
    name: "Aria",
    gender: "female",
    origin: "Italian",
    meaning: "Air, melody",
    personality: ["Musical", "Flowing", "Harmonious", "Artistic"],
    element: "Air",
    color: "#DDA0DD",
    luckyNumbers: [1, 4, 7],
  },
  Cooper: {
    name: "Cooper",
    gender: "male",
    origin: "English",
    meaning: "Barrel maker",
    personality: ["Skilled", "Crafty", "Practical", "Reliable"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [2, 5, 8],
  },
  Naomi: {
    name: "Naomi",
    gender: "female",
    origin: "Hebrew",
    meaning: "Pleasant",
    personality: ["Agreeable", "Kind", "Gentle", "Harmonious"],
    element: "Water",
    color: "#B0E0E6",
    luckyNumbers: [3, 6, 9],
  },
  Ian: {
    name: "Ian",
    gender: "male",
    origin: "Scottish",
    meaning: "God is gracious",
    personality: ["Blessed", "Gracious", "Kind", "Spiritual"],
    element: "Water",
    color: "#5F9EA0",
    luckyNumbers: [1, 5, 8],
  },
  Piper: {
    name: "Piper",
    gender: "female",
    origin: "English",
    meaning: "Pipe player",
    personality: ["Musical", "Artistic", "Expressive", "Creative"],
    element: "Air",
    color: "#9370DB",
    luckyNumbers: [2, 4, 7],
  },
  Jace: {
    name: "Jace",
    gender: "male",
    origin: "Greek",
    meaning: "Healer",
    personality: ["Healing", "Caring", "Nurturing", "Helpful"],
    element: "Water",
    color: "#4682B4",
    luckyNumbers: [3, 6, 9],
  },
  Sadie: {
    name: "Sadie",
    gender: "female",
    origin: "Hebrew",
    meaning: "Princess",
    personality: ["Regal", "Dignified", "Noble", "Graceful"],
    element: "Fire",
    color: "#FF6347",
    luckyNumbers: [1, 5, 8],
  },
  Blake: {
    name: "Blake",
    gender: "unisex",
    origin: "English",
    meaning: "Dark or fair",
    personality: ["Balanced", "Versatile", "Adaptable", "Mysterious"],
    element: "Water",
    color: "#4169E1",
    luckyNumbers: [2, 7, 9],
  },
  Ruby: {
    name: "Ruby",
    gender: "female",
    origin: "Latin",
    meaning: "Red gemstone",
    personality: ["Precious", "Vibrant", "Passionate", "Valuable"],
    element: "Fire",
    color: "#DC143C",
    luckyNumbers: [1, 3, 9],
  },
  Carson: {
    name: "Carson",
    gender: "male",
    origin: "Scottish",
    meaning: "Son of the marsh-dwellers",
    personality: ["Grounded", "Natural", "Adaptable", "Resilient"],
    element: "Earth",
    color: "#556B2F",
    luckyNumbers: [2, 4, 8],
  },
  Alice: {
    name: "Alice",
    gender: "female",
    origin: "Germanic",
    meaning: "Noble",
    personality: ["Dignified", "Respected", "Honorable", "Refined"],
    element: "Air",
    color: "#87CEEB",
    luckyNumbers: [3, 6, 9],
  },
  Xavier: {
    name: "Xavier",
    gender: "male",
    origin: "Arabic",
    meaning: "Bright, splendid",
    personality: ["Brilliant", "Radiant", "Impressive", "Distinguished"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [1, 5, 7],
  },
  Ivy: {
    name: "Ivy",
    gender: "female",
    origin: "English",
    meaning: "Climbing vine",
    personality: ["Growing", "Persistent", "Adaptable", "Enduring"],
    element: "Earth",
    color: "#2E8B57",
    luckyNumbers: [2, 4, 8],
  },
  Easton: {
    name: "Easton",
    gender: "male",
    origin: "English",
    meaning: "East-facing place",
    personality: ["Oriented", "Directional", "Purposeful", "Focused"],
    element: "Air",
    color: "#6495ED",
    luckyNumbers: [3, 6, 9],
  },
  Kaylee: {
    name: "Kaylee",
    gender: "female",
    origin: "Irish",
    meaning: "Slender",
    personality: ["Graceful", "Elegant", "Refined", "Delicate"],
    element: "Air",
    color: "#DDA0DD",
    luckyNumbers: [1, 5, 8],
  },
  Axel: {
    name: "Axel",
    gender: "male",
    origin: "Scandinavian",
    meaning: "Father is peace",
    personality: ["Peaceful", "Calming", "Harmonious", "Stable"],
    element: "Water",
    color: "#4682B4",
    luckyNumbers: [2, 7, 9],
  },
  Madeline: {
    name: "Madeline",
    gender: "female",
    origin: "Hebrew",
    meaning: "Tower",
    personality: ["Strong", "Tall", "Protective", "Stable"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [1, 4, 7],
  },
  Jaxson: {
    name: "Jaxson",
    gender: "male",
    origin: "English",
    meaning: "Son of Jack",
    personality: ["Modern", "Energetic", "Bold", "Distinctive"],
    element: "Fire",
    color: "#FF6347",
    luckyNumbers: [2, 5, 8],
  },
  Cora: {
    name: "Cora",
    gender: "female",
    origin: "Greek",
    meaning: "Maiden",
    personality: ["Pure", "Innocent", "Fresh", "Young"],
    element: "Water",
    color: "#E0FFFF",
    luckyNumbers: [3, 6, 9],
  },
  Brayden: {
    name: "Brayden",
    gender: "male",
    origin: "Irish",
    meaning: "Broad hillside",
    personality: ["Expansive", "Open", "Broad-minded", "Generous"],
    element: "Earth",
    color: "#8FBC8F",
    luckyNumbers: [1, 5, 8],
  },
  Maya: {
    name: "Maya",
    gender: "female",
    origin: "Sanskrit",
    meaning: "Illusion",
    personality: ["Mysterious", "Magical", "Enchanting", "Deep"],
    element: "Water",
    color: "#5F9EA0",
    luckyNumbers: [2, 4, 7],
  },
  Ryder: {
    name: "Ryder",
    gender: "male",
    origin: "English",
    meaning: "Horseman",
    personality: ["Adventurous", "Free", "Independent", "Mobile"],
    element: "Fire",
    color: "#B22222",
    luckyNumbers: [3, 6, 9],
  },
  Ellie: {
    name: "Ellie",
    gender: "female",
    origin: "Greek",
    meaning: "Bright shining one",
    personality: ["Radiant", "Cheerful", "Bright", "Illuminating"],
    element: "Fire",
    color: "#FFD700",
    luckyNumbers: [1, 5, 8],
  },
  Kai: {
    name: "Kai",
    gender: "unisex",
    origin: "Hawaiian",
    meaning: "Ocean",
    personality: ["Flowing", "Deep", "Vast", "Peaceful"],
    element: "Water",
    color: "#4682B4",
    luckyNumbers: [2, 7, 9],
  },
  Kinsley: {
    name: "Kinsley",
    gender: "female",
    origin: "English",
    meaning: "King's meadow",
    personality: ["Regal", "Natural", "Peaceful", "Noble"],
    element: "Earth",
    color: "#8FBC8F",
    luckyNumbers: [1, 4, 7],
  },
  Declan: {
    name: "Declan",
    gender: "male",
    origin: "Irish",
    meaning: "Man of prayer",
    personality: ["Spiritual", "Devoted", "Faithful", "Contemplative"],
    element: "Water",
    color: "#5F9EA0",
    luckyNumbers: [2, 5, 8],
  },
  Genesis: {
    name: "Genesis",
    gender: "female",
    origin: "Greek",
    meaning: "Beginning",
    personality: ["Original", "First", "Creative", "Innovative"],
    element: "Air",
    color: "#9370DB",
    luckyNumbers: [3, 6, 9],
  },
  Levi: {
    name: "Levi",
    gender: "male",
    origin: "Hebrew",
    meaning: "Joined, attached",
    personality: ["Connected", "Loyal", "Bonded", "United"],
    element: "Earth",
    color: "#556B2F",
    luckyNumbers: [1, 5, 8],
  },
  Ariana: {
    name: "Ariana",
    gender: "female",
    origin: "Greek",
    meaning: "Most holy",
    personality: ["Sacred", "Pure", "Spiritual", "Reverent"],
    element: "Air",
    color: "#DDA0DD",
    luckyNumbers: [2, 4, 7],
  },
  Bentley: {
    name: "Bentley",
    gender: "male",
    origin: "English",
    meaning: "Meadow with coarse grass",
    personality: ["Natural", "Grounded", "Resilient", "Practical"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [3, 6, 9],
  },
  Aaliyah: {
    name: "Aaliyah",
    gender: "female",
    origin: "Arabic",
    meaning: "High, exalted",
    personality: ["Elevated", "Noble", "Respected", "Distinguished"],
    element: "Air",
    color: "#87CEEB",
    luckyNumbers: [1, 5, 8],
  },
  Mateo: {
    name: "Mateo",
    gender: "male",
    origin: "Spanish",
    meaning: "Gift of God",
    personality: ["Blessed", "Precious", "Valuable", "Spiritual"],
    element: "Water",
    color: "#4169E1",
    luckyNumbers: [2, 7, 9],
  },
  Serenity: {
    name: "Serenity",
    gender: "female",
    origin: "Latin",
    meaning: "Peaceful",
    personality: ["Calm", "Tranquil", "Harmonious", "Balanced"],
    element: "Water",
    color: "#B0E0E6",
    luckyNumbers: [1, 4, 7],
  },
  Lincoln: {
    name: "Lincoln",
    gender: "male",
    origin: "English",
    meaning: "Town by the pool",
    personality: ["Community-minded", "Peaceful", "Reflective", "Grounded"],
    element: "Water",
    color: "#4682B4",
    luckyNumbers: [2, 5, 8],
  },
  Allison: {
    name: "Allison",
    gender: "female",
    origin: "Germanic",
    meaning: "Noble",
    personality: ["Dignified", "Respected", "Honorable", "Refined"],
    element: "Air",
    color: "#9370DB",
    luckyNumbers: [3, 6, 9],
  },
  Miles: {
    name: "Miles",
    gender: "male",
    origin: "Latin",
    meaning: "Soldier",
    personality: ["Brave", "Disciplined", "Strong", "Protective"],
    element: "Fire",
    color: "#CD5C5C",
    luckyNumbers: [1, 5, 8],
  },
  Gabriella: {
    name: "Gabriella",
    gender: "female",
    origin: "Hebrew",
    meaning: "God is my strength",
    personality: ["Strong", "Spiritual", "Powerful", "Faithful"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [2, 4, 7],
  },
  Silas: {
    name: "Silas",
    gender: "male",
    origin: "Latin",
    meaning: "Wood, forest",
    personality: ["Natural", "Grounded", "Peaceful", "Strong"],
    element: "Earth",
    color: "#2E8B57",
    luckyNumbers: [3, 6, 9],
  },
  Camila: {
    name: "Camila",
    gender: "female",
    origin: "Latin",
    meaning: "Young ceremonial attendant",
    personality: ["Helpful", "Devoted", "Respectful", "Spiritual"],
    element: "Water",
    color: "#5F9EA0",
    luckyNumbers: [1, 5, 8],
  },
  Maverick: {
    name: "Maverick",
    gender: "male",
    origin: "English",
    meaning: "Independent",
    personality: ["Free-spirited", "Unique", "Bold", "Unconventional"],
    element: "Air",
    color: "#6495ED",
    luckyNumbers: [2, 7, 9],
  },
  Nova: {
    name: "Nova",
    gender: "female",
    origin: "Latin",
    meaning: "New star",
    personality: ["Bright", "New", "Shining", "Innovative"],
    element: "Fire",
    color: "#FFD700",
    luckyNumbers: [1, 4, 7],
  },
  Theo: {
    name: "Theo",
    gender: "male",
    origin: "Greek",
    meaning: "Gift of God",
    personality: ["Blessed", "Precious", "Spiritual", "Valuable"],
    element: "Water",
    color: "#4682B4",
    luckyNumbers: [2, 5, 8],
  },
  Willow: {
    name: "Willow",
    gender: "female",
    origin: "English",
    meaning: "Willow tree",
    personality: ["Flexible", "Graceful", "Peaceful", "Natural"],
    element: "Earth",
    color: "#8FBC8F",
    luckyNumbers: [3, 6, 9],
  },
  Felix: {
    name: "Felix",
    gender: "male",
    origin: "Latin",
    meaning: "Happy, lucky",
    personality: ["Joyful", "Fortunate", "Cheerful", "Blessed"],
    element: "Fire",
    color: "#FF6347",
    luckyNumbers: [1, 5, 8],
  },
  Emilia: {
    name: "Emilia",
    gender: "female",
    origin: "Latin",
    meaning: "Rival",
    personality: ["Competitive", "Ambitious", "Driven", "Strong"],
    element: "Fire",
    color: "#CD5C5C",
    luckyNumbers: [2, 4, 7],
  },
  Finn: {
    name: "Finn",
    gender: "male",
    origin: "Irish",
    meaning: "Fair or white",
    personality: ["Pure", "Honest", "Clear", "Bright"],
    element: "Water",
    color: "#E0FFFF",
    luckyNumbers: [3, 6, 9],
  },
  Hazel: {
    name: "Hazel",
    gender: "female",
    origin: "English",
    meaning: "Hazel tree",
    personality: ["Natural", "Wise", "Grounded", "Protective"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [1, 5, 8],
  },
  Milo: {
    name: "Milo",
    gender: "male",
    origin: "Germanic",
    meaning: "Mild, peaceful",
    personality: ["Gentle", "Calm", "Harmonious", "Kind"],
    element: "Water",
    color: "#B0E0E6",
    luckyNumbers: [2, 7, 9],
  },
  Luna: {
    name: "Luna",
    gender: "female",
    origin: "Latin",
    meaning: "Moon",
    personality: ["Mystical", "Cyclical", "Illuminating", "Intuitive"],
    element: "Water",
    color: "#E0FFFF",
    luckyNumbers: [1, 4, 7],
  },
  Jasper: {
    name: "Jasper",
    gender: "male",
    origin: "Persian",
    meaning: "Bringer of treasure",
    personality: ["Valuable", "Precious", "Generous", "Wealthy"],
    element: "Earth",
    color: "#DAA520",
    luckyNumbers: [2, 5, 8],
  },
  Elena: {
    name: "Elena",
    gender: "female",
    origin: "Greek",
    meaning: "Bright, shining light",
    personality: ["Radiant", "Illuminating", "Bright", "Inspiring"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [3, 6, 9],
  },
  Atlas: {
    name: "Atlas",
    gender: "male",
    origin: "Greek",
    meaning: "To bear",
    personality: ["Strong", "Supportive", "Enduring", "Reliable"],
    element: "Earth",
    color: "#556B2F",
    luckyNumbers: [1, 5, 8],
  },
  Iris: {
    name: "Iris",
    gender: "female",
    origin: "Greek",
    meaning: "Rainbow",
    personality: ["Colorful", "Diverse", "Beautiful", "Hopeful"],
    element: "Air",
    color: "#9370DB",
    luckyNumbers: [2, 4, 7],
  },
  Roman: {
    name: "Roman",
    gender: "male",
    origin: "Latin",
    meaning: "Citizen of Rome",
    personality: ["Strong", "Civilized", "Cultured", "Powerful"],
    element: "Fire",
    color: "#B22222",
    luckyNumbers: [3, 6, 9],
  },
  Aurora: {
    name: "Aurora",
    gender: "female",
    origin: "Latin",
    meaning: "Dawn",
    personality: ["New beginnings", "Bright", "Hopeful", "Fresh"],
    element: "Fire",
    color: "#FFD700",
    luckyNumbers: [1, 5, 8],
  },
  Archer: {
    name: "Archer",
    gender: "male",
    origin: "English",
    meaning: "Bowman",
    personality: ["Focused", "Precise", "Skilled", "Determined"],
    element: "Fire",
    color: "#CD5C5C",
    luckyNumbers: [2, 7, 9],
  },
  Emery: {
    name: "Emery",
    gender: "unisex",
    origin: "Germanic",
    meaning: "Brave, powerful",
    personality: ["Courageous", "Strong", "Bold", "Fearless"],
    element: "Fire",
    color: "#FF6347",
    luckyNumbers: [1, 4, 7],
  },
  Sage: {
    name: "Sage",
    gender: "unisex",
    origin: "Latin",
    meaning: "Wise",
    personality: ["Intelligent", "Thoughtful", "Knowledgeable", "Insightful"],
    element: "Air",
    color: "#87CEEB",
    luckyNumbers: [2, 5, 8],
  },
  River: {
    name: "River",
    gender: "unisex",
    origin: "English",
    meaning: "Flowing body of water",
    personality: ["Flowing", "Peaceful", "Natural", "Continuous"],
    element: "Water",
    color: "#4682B4",
    luckyNumbers: [3, 6, 9],
  },
  Phoenix: {
    name: "Phoenix",
    gender: "unisex",
    origin: "Greek",
    meaning: "Rising bird",
    personality: ["Resilient", "Reborn", "Powerful", "Transformative"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [1, 5, 8],
  },
  Rowan: {
    name: "Rowan",
    gender: "unisex",
    origin: "Irish",
    meaning: "Red-haired",
    personality: ["Fiery", "Passionate", "Distinctive", "Bold"],
    element: "Fire",
    color: "#CD5C5C",
    luckyNumbers: [2, 4, 7],
  },
  Wren: {
    name: "Wren",
    gender: "unisex",
    origin: "English",
    meaning: "Small bird",
    personality: ["Delicate", "Musical", "Free", "Joyful"],
    element: "Air",
    color: "#DDA0DD",
    luckyNumbers: [3, 6, 9],
  },
  Indigo: {
    name: "Indigo",
    gender: "unisex",
    origin: "Greek",
    meaning: "Deep blue dye",
    personality: ["Deep", "Mysterious", "Artistic", "Unique"],
    element: "Water",
    color: "#4B0082",
    luckyNumbers: [1, 5, 8],
  },
  Marlowe: {
    name: "Marlowe",
    gender: "unisex",
    origin: "English",
    meaning: "Driftwood",
    personality: ["Natural", "Weathered", "Resilient", "Unique"],
    element: "Water",
    color: "#8B4513",
    luckyNumbers: [2, 7, 9],
  },
  Remi: {
    name: "Remi",
    gender: "unisex",
    origin: "French",
    meaning: "Oarsman",
    personality: ["Navigating", "Skilled", "Determined", "Flowing"],
    element: "Water",
    color: "#5F9EA0",
    luckyNumbers: [1, 4, 7],
  },
  Soren: {
    name: "Soren",
    gender: "male",
    origin: "Danish",
    meaning: "Stern",
    personality: ["Serious", "Thoughtful", "Disciplined", "Strong"],
    element: "Earth",
    color: "#556B2F",
    luckyNumbers: [2, 5, 8],
  },
  Juniper: {
    name: "Juniper",
    gender: "female",
    origin: "Latin",
    meaning: "Young",
    personality: ["Fresh", "Youthful", "Natural", "Vibrant"],
    element: "Earth",
    color: "#2E8B57",
    luckyNumbers: [3, 6, 9],
  },
  Orion: {
    name: "Orion",
    gender: "male",
    origin: "Greek",
    meaning: "Rising in the sky",
    personality: ["Elevated", "Stellar", "Prominent", "Guiding"],
    element: "Air",
    color: "#6495ED",
    luckyNumbers: [1, 5, 8],
  },
  Celeste: {
    name: "Celeste",
    gender: "female",
    origin: "Latin",
    meaning: "Heavenly",
    personality: ["Divine", "Pure", "Elevated", "Spiritual"],
    element: "Air",
    color: "#87CEEB",
    luckyNumbers: [2, 4, 7],
  },
  Zion: {
    name: "Zion",
    gender: "unisex",
    origin: "Hebrew",
    meaning: "Highest point",
    personality: ["Elevated", "Spiritual", "Peak", "Sacred"],
    element: "Air",
    color: "#9370DB",
    luckyNumbers: [3, 6, 9],
  },
  Dahlia: {
    name: "Dahlia",
    gender: "female",
    origin: "Scandinavian",
    meaning: "Valley",
    personality: ["Beautiful", "Colorful", "Natural", "Elegant"],
    element: "Earth",
    color: "#8FBC8F",
    luckyNumbers: [1, 5, 8],
  },
  Knox: {
    name: "Knox",
    gender: "male",
    origin: "Scottish",
    meaning: "Round hill",
    personality: ["Strong", "Grounded", "Protective", "Solid"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [2, 7, 9],
  },
  Magnolia: {
    name: "Magnolia",
    gender: "female",
    origin: "Latin",
    meaning: "Magnol's flower",
    personality: ["Beautiful", "Southern", "Elegant", "Graceful"],
    element: "Earth",
    color: "#E0FFFF",
    luckyNumbers: [1, 4, 7],
  },
  Crew: {
    name: "Crew",
    gender: "male",
    origin: "English",
    meaning: "Group of people",
    personality: ["Social", "Team-oriented", "Cooperative", "United"],
    element: "Air",
    color: "#6495ED",
    luckyNumbers: [2, 5, 8],
  },
  Poppy: {
    name: "Poppy",
    gender: "female",
    origin: "Latin",
    meaning: "Red flower",
    personality: ["Vibrant", "Cheerful", "Bright", "Joyful"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [3, 6, 9],
  },
  Caspian: {
    name: "Caspian",
    gender: "male",
    origin: "English",
    meaning: "White",
    personality: ["Pure", "Vast", "Deep", "Mysterious"],
    element: "Water",
    color: "#4682B4",
    luckyNumbers: [1, 5, 8],
  },
  Clementine: {
    name: "Clementine",
    gender: "female",
    origin: "Latin",
    meaning: "Merciful",
    personality: ["Kind", "Compassionate", "Sweet", "Gentle"],
    element: "Water",
    color: "#FF8C00",
    luckyNumbers: [2, 4, 7],
  },
  Bodhi: {
    name: "Bodhi",
    gender: "male",
    origin: "Sanskrit",
    meaning: "Awakening",
    personality: ["Enlightened", "Spiritual", "Aware", "Peaceful"],
    element: "Air",
    color: "#9370DB",
    luckyNumbers: [3, 6, 9],
  },
  Marigold: {
    name: "Marigold",
    gender: "female",
    origin: "English",
    meaning: "Golden flower",
    personality: ["Bright", "Cheerful", "Golden", "Radiant"],
    element: "Fire",
    color: "#FFD700",
    luckyNumbers: [1, 5, 8],
  },
  Cove: {
    name: "Cove",
    gender: "male",
    origin: "English",
    meaning: "Small bay",
    personality: ["Peaceful", "Protected", "Calm", "Sheltered"],
    element: "Water",
    color: "#5F9EA0",
    luckyNumbers: [2, 7, 9],
  },
  Briar: {
    name: "Briar",
    gender: "unisex",
    origin: "English",
    meaning: "Thorny shrub",
    personality: ["Protective", "Natural", "Strong", "Resilient"],
    element: "Earth",
    color: "#2E8B57",
    luckyNumbers: [1, 4, 7],
  },
  Onyx: {
    name: "Onyx",
    gender: "unisex",
    origin: "Greek",
    meaning: "Black gemstone",
    personality: ["Mysterious", "Strong", "Protective", "Elegant"],
    element: "Earth",
    color: "#000000",
    luckyNumbers: [2, 5, 8],
  },
  Meadow: {
    name: "Meadow",
    gender: "female",
    origin: "English",
    meaning: "Grassland",
    personality: ["Natural", "Peaceful", "Open", "Free"],
    element: "Earth",
    color: "#8FBC8F",
    luckyNumbers: [3, 6, 9],
  },
  Sterling: {
    name: "Sterling",
    gender: "male",
    origin: "English",
    meaning: "High quality",
    personality: ["Excellent", "Valuable", "Pure", "Distinguished"],
    element: "Air",
    color: "#C0C0C0",
    luckyNumbers: [1, 5, 8],
  },
  Fern: {
    name: "Fern",
    gender: "female",
    origin: "English",
    meaning: "Feathery plant",
    personality: ["Delicate", "Natural", "Green", "Graceful"],
    element: "Earth",
    color: "#2E8B57",
    luckyNumbers: [2, 4, 7],
  },
  Blaze: {
    name: "Blaze",
    gender: "male",
    origin: "English",
    meaning: "Flame",
    personality: ["Fiery", "Passionate", "Bright", "Energetic"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [3, 6, 9],
  },
  Wisteria: {
    name: "Wisteria",
    gender: "female",
    origin: "English",
    meaning: "Climbing flower",
    personality: ["Beautiful", "Climbing", "Graceful", "Persistent"],
    element: "Earth",
    color: "#9370DB",
    luckyNumbers: [1, 5, 8],
  },
  Canyon: {
    name: "Canyon",
    gender: "male",
    origin: "Spanish",
    meaning: "Deep valley",
    personality: ["Deep", "Strong", "Natural", "Majestic"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [2, 7, 9],
  },
  Azalea: {
    name: "Azalea",
    gender: "female",
    origin: "Greek",
    meaning: "Dry flower",
    personality: ["Beautiful", "Resilient", "Colorful", "Enduring"],
    element: "Fire",
    color: "#FF69B4",
    luckyNumbers: [1, 4, 7],
  },
  Ridge: {
    name: "Ridge",
    gender: "male",
    origin: "English",
    meaning: "Mountain crest",
    personality: ["High", "Strong", "Prominent", "Elevated"],
    element: "Earth",
    color: "#556B2F",
    luckyNumbers: [2, 5, 8],
  },
  Blossom: {
    name: "Blossom",
    gender: "female",
    origin: "English",
    meaning: "Flower bloom",
    personality: ["Blooming", "Fresh", "Beautiful", "Growing"],
    element: "Earth",
    color: "#FFB6C1",
    luckyNumbers: [3, 6, 9],
  },
  Vale: {
    name: "Vale",
    gender: "unisex",
    origin: "Latin",
    meaning: "Valley",
    personality: ["Peaceful", "Low", "Humble", "Sheltered"],
    element: "Earth",
    color: "#8FBC8F",
    luckyNumbers: [1, 5, 8],
  },
  Coral: {
    name: "Coral",
    gender: "female",
    origin: "Latin",
    meaning: "Sea growth",
    personality: ["Ocean-like", "Colorful", "Natural", "Vibrant"],
    element: "Water",
    color: "#FF7F50",
    luckyNumbers: [2, 4, 7],
  },
  Flint: {
    name: "Flint",
    gender: "male",
    origin: "English",
    meaning: "Hard rock",
    personality: ["Strong", "Durable", "Sparking", "Reliable"],
    element: "Earth",
    color: "#696969",
    luckyNumbers: [3, 6, 9],
  },
  Jasmine: {
    name: "Jasmine",
    gender: "female",
    origin: "Persian",
    meaning: "Fragrant flower",
    personality: ["Sweet", "Fragrant", "Beautiful", "Delicate"],
    element: "Earth",
    color: "#F8F8FF",
    luckyNumbers: [1, 5, 8],
  },
  Stone: {
    name: "Stone",
    gender: "male",
    origin: "English",
    meaning: "Rock",
    personality: ["Solid", "Strong", "Enduring", "Grounded"],
    element: "Earth",
    color: "#808080",
    luckyNumbers: [2, 7, 9],
  },
  Peony: {
    name: "Peony",
    gender: "female",
    origin: "Greek",
    meaning: "Healing flower",
    personality: ["Healing", "Beautiful", "Lush", "Nurturing"],
    element: "Earth",
    color: "#FFB6C1",
    luckyNumbers: [1, 4, 7],
  },
  Slate: {
    name: "Slate",
    gender: "male",
    origin: "English",
    meaning: "Gray rock",
    personality: ["Smooth", "Clean", "Fresh start", "Neutral"],
    element: "Earth",
    color: "#708090",
    luckyNumbers: [2, 5, 8],
  },
  Zinnia: {
    name: "Zinnia",
    gender: "female",
    origin: "Latin",
    meaning: "Flower",
    personality: ["Colorful", "Bright", "Cheerful", "Lasting"],
    element: "Fire",
    color: "#FF1493",
    luckyNumbers: [3, 6, 9],
  },
  Cliff: {
    name: "Cliff",
    gender: "male",
    origin: "English",
    meaning: "Steep rock face",
    personality: ["Strong", "High", "Dramatic", "Solid"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [1, 5, 8],
  },
  Camellia: {
    name: "Camellia",
    gender: "female",
    origin: "Latin",
    meaning: "Flower",
    personality: ["Elegant", "Beautiful", "Refined", "Graceful"],
    element: "Earth",
    color: "#FFB6C1",
    luckyNumbers: [2, 4, 7],
  },
  Grove: {
    name: "Grove",
    gender: "male",
    origin: "English",
    meaning: "Small wood",
    personality: ["Natural", "Peaceful", "Sheltered", "Growing"],
    element: "Earth",
    color: "#228B22",
    luckyNumbers: [3, 6, 9],
  },
  Amaryllis: {
    name: "Amaryllis",
    gender: "female",
    origin: "Greek",
    meaning: "Sparkling flower",
    personality: ["Sparkling", "Beautiful", "Dramatic", "Bold"],
    element: "Fire",
    color: "#DC143C",
    luckyNumbers: [1, 5, 8],
  },
  Dune: {
    name: "Dune",
    gender: "male",
    origin: "English",
    meaning: "Sand hill",
    personality: ["Shifting", "Natural", "Warm", "Flowing"],
    element: "Earth",
    color: "#F4A460",
    luckyNumbers: [2, 7, 9],
  },
  Gardenia: {
    name: "Gardenia",
    gender: "female",
    origin: "English",
    meaning: "Garden flower",
    personality: ["Fragrant", "Pure", "Beautiful", "Elegant"],
    element: "Earth",
    color: "#F8F8FF",
    luckyNumbers: [1, 4, 7],
  },
  Summit: {
    name: "Summit",
    gender: "male",
    origin: "English",
    meaning: "Highest point",
    personality: ["Peak", "Achieving", "High", "Successful"],
    element: "Air",
    color: "#87CEEB",
    luckyNumbers: [2, 5, 8],
  },
  Hibiscus: {
    name: "Hibiscus",
    gender: "female",
    origin: "Greek",
    meaning: "Marsh mallow",
    personality: ["Tropical", "Vibrant", "Exotic", "Beautiful"],
    element: "Fire",
    color: "#FF69B4",
    luckyNumbers: [3, 6, 9],
  },
  Canyon: {
    name: "Canyon",
    gender: "male",
    origin: "Spanish",
    meaning: "Deep valley",
    personality: ["Deep", "Strong", "Natural", "Majestic"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [1, 5, 8],
  },
  Lotus: {
    name: "Lotus",
    gender: "female",
    origin: "Greek",
    meaning: "Water lily",
    personality: ["Pure", "Spiritual", "Rising", "Beautiful"],
    element: "Water",
    color: "#FFB6C1",
    luckyNumbers: [2, 4, 7],
  },
  Aspen: {
    name: "Aspen",
    gender: "unisex",
    origin: "English",
    meaning: "Quaking tree",
    personality: ["Trembling", "Sensitive", "Natural", "Graceful"],
    element: "Earth",
    color: "#F5F5DC",
    luckyNumbers: [3, 6, 9],
  },
  Magnolia: {
    name: "Magnolia",
    gender: "female",
    origin: "Latin",
    meaning: "Magnol's flower",
    personality: ["Beautiful", "Southern", "Elegant", "Graceful"],
    element: "Earth",
    color: "#F8F8FF",
    luckyNumbers: [1, 5, 8],
  },
  Forest: {
    name: "Forest",
    gender: "male",
    origin: "English",
    meaning: "Woods",
    personality: ["Natural", "Deep", "Mysterious", "Growing"],
    element: "Earth",
    color: "#228B22",
    luckyNumbers: [2, 7, 9],
  },
  Orchid: {
    name: "Orchid",
    gender: "female",
    origin: "Greek",
    meaning: "Flower",
    personality: ["Exotic", "Delicate", "Beautiful", "Rare"],
    element: "Air",
    color: "#DA70D6",
    luckyNumbers: [1, 4, 7],
  },
  River: {
    name: "River",
    gender: "unisex",
    origin: "English",
    meaning: "Flowing water",
    personality: ["Flowing", "Peaceful", "Natural", "Continuous"],
    element: "Water",
    color: "#4682B4",
    luckyNumbers: [2, 5, 8],
  },
  Rose: {
    name: "Rose",
    gender: "female",
    origin: "Latin",
    meaning: "Flower",
    personality: ["Beautiful", "Romantic", "Fragrant", "Classic"],
    element: "Earth",
    color: "#FF69B4",
    luckyNumbers: [3, 6, 9],
  },
  Ocean: {
    name: "Ocean",
    gender: "unisex",
    origin: "Greek",
    meaning: "Sea",
    personality: ["Vast", "Deep", "Powerful", "Mysterious"],
    element: "Water",
    color: "#006994",
    luckyNumbers: [1, 5, 8],
  },
  Tulip: {
    name: "Tulip",
    gender: "female",
    origin: "Persian",
    meaning: "Turban",
    personality: ["Colorful", "Spring-like", "Fresh", "Beautiful"],
    element: "Earth",
    color: "#FF69B4",
    luckyNumbers: [2, 4, 7],
  },
  Sky: {
    name: "Sky",
    gender: "unisex",
    origin: "English",
    meaning: "Atmosphere",
    personality: ["Limitless", "Open", "Free", "Expansive"],
    element: "Air",
    color: "#87CEEB",
    luckyNumbers: [3, 6, 9],
  },
  Violet: {
    name: "Violet",
    gender: "female",
    origin: "Latin",
    meaning: "Purple flower",
    personality: ["Delicate", "Beautiful", "Modest", "Graceful"],
    element: "Earth",
    color: "#8A2BE2",
    luckyNumbers: [1, 5, 8],
  },
  Storm: {
    name: "Storm",
    gender: "unisex",
    origin: "English",
    meaning: "Tempest",
    personality: ["Powerful", "Dynamic", "Intense", "Dramatic"],
    element: "Air",
    color: "#708090",
    luckyNumbers: [2, 7, 9],
  },
  Daisy: {
    name: "Daisy",
    gender: "female",
    origin: "English",
    meaning: "Day's eye",
    personality: ["Cheerful", "Innocent", "Fresh", "Simple"],
    element: "Earth",
    color: "#FFFF00",
    luckyNumbers: [1, 4, 7],
  },
  Rain: {
    name: "Rain",
    gender: "unisex",
    origin: "English",
    meaning: "Precipitation",
    personality: ["Refreshing", "Cleansing", "Nurturing", "Life-giving"],
    element: "Water",
    color: "#4682B4",
    luckyNumbers: [2, 5, 8],
  },
  Lily: {
    name: "Lily",
    gender: "female",
    origin: "English",
    meaning: "Pure flower",
    personality: ["Pure", "Innocent", "Beautiful", "Graceful"],
    element: "Water",
    color: "#FFFFFF",
    luckyNumbers: [3, 6, 9],
  },
  Thunder: {
    name: "Thunder",
    gender: "male",
    origin: "English",
    meaning: "Storm sound",
    personality: ["Powerful", "Loud", "Dramatic", "Strong"],
    element: "Air",
    color: "#2F4F4F",
    luckyNumbers: [1, 5, 8],
  },
  Sunflower: {
    name: "Sunflower",
    gender: "female",
    origin: "English",
    meaning: "Sun flower",
    personality: ["Bright", "Cheerful", "Following light", "Tall"],
    element: "Fire",
    color: "#FFD700",
    luckyNumbers: [2, 4, 7],
  },
  Breeze: {
    name: "Breeze",
    gender: "unisex",
    origin: "English",
    meaning: "Gentle wind",
    personality: ["Gentle", "Refreshing", "Light", "Flowing"],
    element: "Air",
    color: "#E0FFFF",
    luckyNumbers: [3, 6, 9],
  },
  Jasmine: {
    name: "Jasmine",
    gender: "female",
    origin: "Persian",
    meaning: "Fragrant flower",
    personality: ["Sweet", "Fragrant", "Beautiful", "Delicate"],
    element: "Earth",
    color: "#F8F8FF",
    luckyNumbers: [1, 5, 8],
  },
  Frost: {
    name: "Frost",
    gender: "male",
    origin: "English",
    meaning: "Frozen dew",
    personality: ["Cool", "Crisp", "Clear", "Crystalline"],
    element: "Water",
    color: "#F0F8FF",
    luckyNumbers: [2, 7, 9],
  },
  Iris: {
    name: "Iris",
    gender: "female",
    origin: "Greek",
    meaning: "Rainbow",
    personality: ["Colorful", "Diverse", "Beautiful", "Hopeful"],
    element: "Air",
    color: "#9370DB",
    luckyNumbers: [1, 4, 7],
  },
  Blaze: {
    name: "Blaze",
    gender: "male",
    origin: "English",
    meaning: "Flame",
    personality: ["Fiery", "Passionate", "Bright", "Energetic"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [2, 5, 8],
  },
  Poppy: {
    name: "Poppy",
    gender: "female",
    origin: "Latin",
    meaning: "Red flower",
    personality: ["Vibrant", "Cheerful", "Bright", "Joyful"],
    element: "Fire",
    color: "#FF4500",
    luckyNumbers: [3, 6, 9],
  },
  Ember: {
    name: "Ember",
    gender: "unisex",
    origin: "English",
    meaning: "Burning coal",
    personality: ["Glowing", "Warm", "Lasting", "Passionate"],
    element: "Fire",
    color: "#DC143C",
    luckyNumbers: [1, 5, 8],
  },
  Marigold: {
    name: "Marigold",
    gender: "female",
    origin: "English",
    meaning: "Golden flower",
    personality: ["Bright", "Cheerful", "Golden", "Radiant"],
    element: "Fire",
    color: "#FFD700",
    luckyNumbers: [2, 4, 7],
  },
  Flint: {
    name: "Flint",
    gender: "male",
    origin: "English",
    meaning: "Hard rock",
    personality: ["Strong", "Durable", "Sparking", "Reliable"],
    element: "Earth",
    color: "#696969",
    luckyNumbers: [3, 6, 9],
  },
  Peony: {
    name: "Peony",
    gender: "female",
    origin: "Greek",
    meaning: "Healing flower",
    personality: ["Healing", "Beautiful", "Lush", "Nurturing"],
    element: "Earth",
    color: "#FFB6C1",
    luckyNumbers: [1, 5, 8],
  },
  Ash: {
    name: "Ash",
    gender: "unisex",
    origin: "English",
    meaning: "Tree",
    personality: ["Strong", "Flexible", "Enduring", "Natural"],
    element: "Earth",
    color: "#B2BEB5",
    luckyNumbers: [2, 7, 9],
  },
  Zinnia: {
    name: "Zinnia",
    gender: "female",
    origin: "Latin",
    meaning: "Flower",
    personality: ["Colorful", "Bright", "Cheerful", "Lasting"],
    element: "Fire",
    color: "#FF1493",
    luckyNumbers: [1, 4, 7],
  },
  Stone: {
    name: "Stone",
    gender: "male",
    origin: "English",
    meaning: "Rock",
    personality: ["Solid", "Strong", "Enduring", "Grounded"],
    element: "Earth",
    color: "#808080",
    luckyNumbers: [2, 5, 8],
  },
  Camellia: {
    name: "Camellia",
    gender: "female",
    origin: "Latin",
    meaning: "Flower",
    personality: ["Elegant", "Beautiful", "Refined", "Graceful"],
    element: "Earth",
    color: "#FFB6C1",
    luckyNumbers: [3, 6, 9],
  },
  Clay: {
    name: "Clay",
    gender: "male",
    origin: "English",
    meaning: "Earth material",
    personality: ["Moldable", "Earthy", "Creative", "Grounded"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [1, 5, 8],
  },
  Amaryllis: {
    name: "Amaryllis",
    gender: "female",
    origin: "Greek",
    meaning: "Sparkling flower",
    personality: ["Sparkling", "Beautiful", "Dramatic", "Bold"],
    element: "Fire",
    color: "#DC143C",
    luckyNumbers: [2, 4, 7],
  },
  Reed: {
    name: "Reed",
    gender: "male",
    origin: "English",
    meaning: "Red-haired",
    personality: ["Flexible", "Musical", "Natural", "Flowing"],
    element: "Water",
    color: "#8FBC8F",
    luckyNumbers: [3, 6, 9],
  },
  Gardenia: {
    name: "Gardenia",
    gender: "female",
    origin: "English",
    meaning: "Garden flower",
    personality: ["Fragrant", "Pure", "Beautiful", "Elegant"],
    element: "Earth",
    color: "#F8F8FF",
    luckyNumbers: [1, 5, 8],
  },
  Slate: {
    name: "Slate",
    gender: "male",
    origin: "English",
    meaning: "Gray rock",
    personality: ["Smooth", "Clean", "Fresh start", "Neutral"],
    element: "Earth",
    color: "#708090",
    luckyNumbers: [2, 7, 9],
  },
  Hibiscus: {
    name: "Hibiscus",
    gender: "female",
    origin: "Greek",
    meaning: "Marsh mallow",
    personality: ["Tropical", "Vibrant", "Exotic", "Beautiful"],
    element: "Fire",
    color: "#FF69B4",
    luckyNumbers: [1, 4, 7],
  },
  Cliff: {
    name: "Cliff",
    gender: "male",
    origin: "English",
    meaning: "Steep rock face",
    personality: ["Strong", "High", "Dramatic", "Solid"],
    element: "Earth",
    color: "#8B4513",
    luckyNumbers: [2, 5, 8],
  },
  Lotus: {
    name: "Lotus",
    gender: "female",
    origin: "Greek",
    meaning: "Water lily",
    personality: ["Pure", "Spiritual", "Rising", "Beautiful"],
    element: "Water",
    color: "#FFB6C1",
    luckyNumbers: [3, 6, 9],
  },
  Dune: {
    name: "Dune",
    gender: "male",
    origin: "English",
    meaning: "Sand hill",
    personality: ["Shifting", "Natural", "Warm", "Flowing"],
    element: "Earth",
    color: "#F4A460",
    luckyNumbers: [1, 5, 8],
  },
  Orchid: {
    name: "Orchid",
    gender: "female",
    origin: "Greek",
    meaning: "Flower",
    personality: ["Exotic", "Delicate", "Beautiful", "Rare"],
    element: "Air",
    color: "#DA70D6",
    luckyNumbers: [2, 4, 7],
  },
  Grove: {
    name: "Grove",
    gender: "male",
    origin: "English",
    meaning: "Small wood",
    personality: ["Natural", "Peaceful", "Sheltered", "Growing"],
    element: "Earth",
    color: "#228B22",
    luckyNumbers: [3, 6, 9],
  },
  Tulip: {
    name: "Tulip",
    gender: "female",
    origin: "Persian",
    meaning: "Turban",
    personality: ["Colorful", "Spring-like", "Fresh", "Beautiful"],
    element: "Earth",
    color: "#FF69B4",
    luckyNumbers: [1, 5, 8],
  },
  Summit: {
    name: "Summit",
    gender: "male",
    origin: "English",
    meaning: "Highest point",
    personality: ["Peak", "Achieving", "High", "Successful"],
    element: "Air",
    color: "#87CEEB",
    luckyNumbers: [2, 7, 9],
  },
  Sunflower: {
    name: "Sunflower",
    gender: "female",
    origin: "English",
    meaning: "Sun flower",
    personality: ["Bright", "Cheerful", "Following light", "Tall"],
    element: "Fire",
    color: "#FFD700",
    luckyNumbers: [1, 4, 7],
  },
}

export function getNameMeaning(name: string): NameMeaning | null {
  const normalizedName = name.charAt(0).toUpperCase() + name.slice(1).toLowerCase()
  return nameMeanings[normalizedName] || null
}

export function calculateNameCompatibility(
  name1: string,
  name2: string,
): {
  score: number
  analysis: string
  sharedTraits: string[]
  complementaryTraits: string[]
} {
  const meaning1 = getNameMeaning(name1)
  const meaning2 = getNameMeaning(name2)

  if (!meaning1 || !meaning2) {
    return {
      score: 50,
      analysis: "Unable to calculate compatibility - one or both names not found in our database.",
      sharedTraits: [],
      complementaryTraits: [],
    }
  }

  // Element compatibility
  const elementCompatibility: Record<string, Record<string, number>> = {
    Fire: { Fire: 70, Water: 30, Earth: 50, Air: 90 },
    Water: { Fire: 30, Water: 80, Earth: 90, Air: 50 },
    Earth: { Fire: 50, Water: 90, Earth: 70, Air: 30 },
    Air: { Fire: 90, Water: 50, Earth: 30, Air: 80 },
  }

  const elementScore = elementCompatibility[meaning1.element][meaning2.element]

  // Shared traits
  const sharedTraits = meaning1.personality.filter((trait) => meaning2.personality.includes(trait))

  // Complementary traits (opposite but compatible)
  const complementaryPairs: Record<string, string[]> = {
    Confident: ["Gentle", "Modest"],
    Gentle: ["Confident", "Strong"],
    Creative: ["Practical", "Organized"],
    Practical: ["Creative", "Artistic"],
    Leader: ["Supportive", "Follower"],
    Supportive: ["Leader", "Independent"],
    Independent: ["Nurturing", "Caring"],
    Nurturing: ["Independent", "Strong"],
    Energetic: ["Calm", "Peaceful"],
    Calm: ["Energetic", "Vibrant"],
    Analytical: ["Intuitive", "Emotional"],
    Intuitive: ["Analytical", "Logical"],
    Outgoing: ["Reserved", "Quiet"],
    Reserved: ["Outgoing", "Social"],
    Ambitious: ["Content", "Peaceful"],
    Content: ["Ambitious", "Driven"],
  }

  const complementaryTraits: string[] = []
  meaning1.personality.forEach((trait1) => {
    meaning2.personality.forEach((trait2) => {
      if (complementaryPairs[trait1]?.includes(trait2)) {
        complementaryTraits.push(`${trait1} + ${trait2}`)
      }
    })
  })

  // Calculate final score
  let score = elementScore
  score += sharedTraits.length * 5 // Bonus for shared traits
  score += complementaryTraits.length * 3 // Bonus for complementary traits

  // Ensure score is between 0 and 100
  score = Math.min(100, Math.max(0, score))

  // Generate analysis
  let analysis = ""
  if (score >= 80) {
    analysis = "Excellent compatibility! Your names suggest a harmonious and balanced relationship."
  } else if (score >= 60) {
    analysis = "Good compatibility! You share many positive traits and complement each other well."
  } else if (score >= 40) {
    analysis = "Moderate compatibility. With understanding and effort, you can build a strong relationship."
  } else {
    analysis = "Challenging compatibility. Your differences may require extra communication and compromise."
  }

  return {
    score,
    analysis,
    sharedTraits,
    complementaryTraits,
  }
}
